[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://credmarvi.netlify.app"
  NEXT_PUBLIC_APP_ENV = "production"

[context.branch-deploy.environment]
  NEXT_PUBLIC_APP_ENV = "development"

[context.deploy-preview.environment]
  NEXT_PUBLIC_APP_ENV = "development"
