import Link from "next/link";
import {Container} from "../common/Container";
import {Logo} from "../brand/Logo";
import {siteConfig} from "@/lib/site-config";
import {siteContactMessage,whatsappUrl} from "@/lib/whatsapp";

const navigation=[["Soluções","/solucoes"],["Para você","/analise?profile=PERSON"],["Para empresas","/analise?profile=BUSINESS"],["Especialista","/#especialista"],["Segurança","/#seguranca"],["Privacidade","/privacidade"],["Termos","/termos"],["Contato","/contato"]];

export function Footer(){return <footer className="bg-[#0d0f11] py-16 text-slate-300"><Container><div className="grid gap-12 border-b border-white/10 pb-12 md:grid-cols-[1.25fr_1fr_1fr]"><div><Logo light descriptor/><p className="mt-6 max-w-sm text-sm leading-7">Atendimento consultivo para pessoas e empresas, conectando necessidades reais a soluções financeiras adequadas.</p><p className="mt-5 flex items-center gap-2 text-xs text-slate-400"><span className="h-px w-8 bg-gold"/>Segurança, clareza e atendimento humano.</p></div><div><h2 className="text-sm font-semibold text-white">Navegação</h2><div className="mt-5 grid grid-cols-2 gap-x-6 gap-y-3 text-sm">{navigation.map(([label,href])=><Link className="transition hover:text-gold" key={href} href={href}>{label}</Link>)}</div></div><div><h2 className="text-sm font-semibold text-white">Canais oficiais</h2><a href={whatsappUrl(siteContactMessage())} target="_blank" rel="noreferrer" className="mt-5 inline-flex text-sm font-semibold text-white transition hover:text-gold">WhatsApp oficial</a>{siteConfig.email&&<a className="mt-3 block text-sm transition hover:text-white" href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a>}{siteConfig.cnpj&&<p className="mt-3 text-sm">CNPJ {siteConfig.cnpj}</p>}<div className="mt-6 flex gap-4 text-xs"><Link href="/privacidade">Privacidade</Link><Link href="/termos">Termos</Link></div></div></div><div className="flex flex-col gap-2 pt-7 text-xs leading-5 text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>A disponibilidade, aprovação, taxas e condições dependem das instituições responsáveis. © {new Date().getFullYear()} {siteConfig.brand.name}.</p><p className="shrink-0">Tecnologia desenvolvida pelo {siteConfig.technologyProviderName}.</p></div></Container></footer>}
