"use client";
import {useEffect,useMemo,useState} from "react";
import {useSearchParams} from "next/navigation";
import Link from "next/link";
import {ArrowLeft,ArrowRight,Building2,Check,Clock,LockKeyhole,MessageCircle,ShieldCheck,UserRound} from "lucide-react";
import {Logo} from "@/components/brand/Logo";
import {maskPhone} from "@/lib/formatting";
import {objectivesFor,objectiveById} from "@/lib/domain/objectives";
import {contextFromSearch,flowLabel,flowSteps,setFlowProfile,type FlowAnswers,type FlowState,type FlowStepId} from "@/lib/flow-engine";
import {createProtocol} from "@/lib/protocol";
import {handoffMessage,whatsappUrl} from "@/lib/whatsapp";
import {trackEvent} from "@/lib/analytics";

const answerLabels:Record<string,string>={UP_TO_50:"Até R$ 50 mil","50_TO_200":"R$ 50 mil a R$ 200 mil","200_TO_500":"R$ 200 mil a R$ 500 mil",ABOVE_500:"Acima de R$ 500 mil",UNSURE:"Ainda não sei",NOW:"O quanto antes","30_DAYS":"Nos próximos 30 dias","3_MONTHS":"Em até 3 meses",PLANNING:"Estou apenas planejando",FIRST:"Comprar meu primeiro veículo",TRADE:"Trocar o veículo atual",CHOSEN:"Financiar um veículo que já escolhi",RESEARCH:"Ainda estou pesquisando",HOME:"Imóvel",VEHICLE:"Veículo",HEAVY:"Veículo pesado",SERVICE:"Serviço"};

export function LeadWizard(){
 const search=useSearchParams(),quick=search.get("quick")==="1";
 const initialContext=useMemo(()=>contextFromSearch(search),[search]);
 const[state,setState]=useState<FlowState>({context:initialContext,answers:{},completed:[]}),[history,setHistory]=useState<FlowStepId[]>([]),[error,setError]=useState(""),[selectedKey,setSelectedKey]=useState(""),[done,setDone]=useState<{protocol:string;url:string}>();
 useEffect(()=>{trackEvent("flow_started",{entryPoint:initialContext.entryPoint});trackEvent("flow_context_loaded",{entryPoint:initialContext.entryPoint,profile:initialContext.profile||"unknown",objective:initialContext.objectiveId||"unknown",product:initialContext.productId||"unknown"})},[initialContext]);
 const steps=flowSteps(state),current=quick?(state.answers.name&&state.answers.phone&&state.answers.serviceConsent?steps.find(step=>step.id==="review")!:steps.find(step=>step.id==="contact")!):steps[0];
 const progress=current.id==="review"?100:Math.max(20,Math.round(((history.length+1)/(history.length+steps.length))*100));
 const updateAnswer=<K extends keyof FlowAnswers>(key:K,value:FlowAnswers[K])=>{setState(old=>({...old,answers:{...old.answers,[key]:value}}));setError("")};
 function advance(id:FlowStepId,delay=0){setState(old=>({...old,completed:[...(old.completed||[]),id]}));setHistory(old=>[...old,id]);trackEvent("wizard_step_completed",{step:id});if(delay)window.setTimeout(()=>window.scrollTo({top:0,behavior:"smooth"}),delay);else window.scrollTo({top:0,behavior:"smooth"})}
 function choose(stepId:FlowStepId,value:string){
  if(selectedKey)return;setSelectedKey(`${stepId}:${value}`);setError("");
  window.setTimeout(()=>{if(stepId==="profile"){setState(old=>setFlowProfile(old,value as "PERSON"|"BUSINESS"));trackEvent("profile_selected",{profile:value});}else if(stepId==="objective"){setState(old=>({...old,context:{...old.context,objectiveId:value},answers:{...old.answers}}));trackEvent("objective_selected",{profile:state.context.profile||"unknown"});}else setState(old=>({...old,answers:{...old.answers,[stepId]:value}}));setState(old=>({...old,completed:[...(old.completed||[]),stepId]}));setHistory(old=>[...old,stepId]);setSelectedKey("");window.scrollTo({top:0,behavior:"smooth"})},180);
 }
 function validateAndAdvance(){
  if(current.id==="context"&&(!state.answers.context||state.answers.context.trim().length<5))return setError("Conte um pouco mais para prepararmos o atendimento.");
  if(current.id==="contact"){if(!state.answers.name||state.answers.name.trim().length<3)return setError("Informe seu nome.");if((state.answers.phone||"").replace(/\D/g,"").length<10)return setError("Informe um WhatsApp com DDD.");if(!state.answers.serviceConsent)return setError("Aceite o Aviso de Privacidade para continuar.")}
  advance(current.id);
 }
 function back(){const previous=history.at(-1);if(!previous)return window.history.back();setHistory(old=>old.slice(0,-1));setState(old=>{const answers={...old.answers};if(previous in answers)delete answers[previous as keyof FlowAnswers];const completed=(old.completed||[]).filter(id=>id!==previous);if(previous==="objective")return{context:{...old.context,objectiveId:undefined,productId:undefined,categoryId:undefined},answers,completed};if(previous==="profile")return{context:{...old.context,profile:undefined,objectiveId:undefined,productId:undefined,categoryId:undefined},answers:{},completed};return{...old,answers,completed}});setError("")}
 function submit(){const protocol=createProtocol(),profile=state.context.profile==="BUSINESS"?"Empresa":state.context.profile==="PERSON"?"Pessoa física":"Não informado",subject=flowLabel(state.context),url=whatsappUrl(handoffMessage(protocol,profile,subject));trackEvent("lead_submit_success",{result:"whatsapp"});setDone({protocol,url});window.open(url,"_blank","noopener,noreferrer")}
 if(done)return <Shell progress={100} onBack={()=>undefined}><div className="text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-gold/15 text-[#8b6a16]"><Check size={32}/></span><p className="eyebrow mt-7">Atendimento preparado</p><h1 className="mt-3 font-serif text-4xl font-semibold">Pronto. A Marlise já pode começar conhecendo seu contexto.</h1><p className="mx-auto mt-4 max-w-xl leading-7 text-muted">Seu protocolo identifica o atendimento sem expor informações financeiras na URL.</p><div className="mx-auto mt-7 max-w-sm rounded-2xl border bg-cream p-5"><span className="text-xs font-bold uppercase tracking-wider text-muted">Protocolo</span><strong className="mt-2 block text-xl">{done.protocol}</strong></div><a href={done.url} target="_blank" rel="noopener noreferrer" className="btn-primary mt-8"><MessageCircle size={18}/>Continuar com a Marlise</a><div className="mt-12 border-t pt-8"><p className="text-sm font-bold">A Marvi também pode ajudar em outros momentos.</p><div className="mt-4 flex flex-wrap justify-center gap-2"><Link className="rounded-full border px-4 py-2 text-sm" href="/analise?profile=PERSON&objective=plan-purchase">Planejar uma aquisição</Link><Link className="rounded-full border px-4 py-2 text-sm" href="/analise?profile=PERSON&objective=protect-family">Proteger patrimônio</Link><Link className="rounded-full border px-4 py-2 text-sm" href="/analise?profile=BUSINESS">Soluções para sua empresa</Link></div></div></div></Shell>;
 return <Shell progress={progress} onBack={back}><div className="mb-7"><p className="eyebrow">{flowLabel(state.context)}</p>{state.context.objectiveId&&current.id!=="review"&&<p className="mt-2 text-sm font-semibold text-muted">Entendi. Vamos preparar seu atendimento sem repetir o que você já informou.</p>}</div><section key={current.id} className="animate-[flowIn_.2s_ease-out]"><h1 className="max-w-2xl font-serif text-3xl font-semibold leading-tight sm:text-4xl">{current.question}</h1>{current.helper&&<p className="mt-3 max-w-xl text-sm leading-6 text-muted">{current.helper}</p>}<div className="mt-8"><StepContent stepId={current.id} state={state} options={current.options} choose={choose} update={updateAnswer}/></div>{error&&<p role="alert" aria-live="polite" className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-[#a52d34]">{error}</p>}<div className="mt-9 flex items-center justify-end">{current.type==="TEXT"||current.type==="CONTACT"?<button className="btn-primary" onClick={validateAndAdvance}>Preparar atendimento <ArrowRight size={18}/></button>:current.type==="REVIEW"?<button className="btn-primary" onClick={submit}><MessageCircle size={18}/>Continuar com a Marlise</button>:null}</div>{!quick&&current.id!=="contact"&&current.id!=="review"&&<Link href="/analise?quick=1&entryPoint=SPECIALIST" className="mt-7 block text-center text-sm font-bold text-[#80600f] underline">Prefiro falar direto com a Marlise</Link>}</section></Shell>
}

function StepContent({stepId,state,options,choose,update}:{stepId:FlowStepId;state:FlowState;options?:{value:string;label:string}[];choose:(id:FlowStepId,value:string)=>void;update:<K extends keyof FlowAnswers>(key:K,value:FlowAnswers[K])=>void}){
 if(stepId==="profile")return <div className="grid gap-3 sm:grid-cols-2"><Option icon={<UserRound/>} label="Para mim" onClick={()=>choose("profile","PERSON")}/><Option icon={<Building2/>} label="Para minha empresa" onClick={()=>choose("profile","BUSINESS")}/></div>;
 if(stepId==="objective"){const profile=state.context.profile||"PERSON";return <div className="grid gap-3">{objectivesFor(profile).map(item=><Option key={item.id} label={item.title} text={item.shortDescription} onClick={()=>choose("objective",item.id)}/>)}</div>}
 if(options)return <div className="grid gap-3 sm:grid-cols-2">{options.map(item=><Option key={item.value} label={item.label} onClick={()=>choose(stepId,item.value)}/>)}</div>;
 if(stepId==="context")return <label><span className="sr-only">Explique sua necessidade</span><textarea autoFocus className="field min-h-32 py-3" maxLength={500} value={state.answers.context||""} onChange={event=>update("context",event.target.value)} placeholder="Ex.: quero organizar uma aquisição para os próximos meses"/><span className="mt-2 block text-right text-xs text-muted">{state.answers.context?.length||0}/500</span></label>;
 if(stepId==="contact")return <div><div className="grid gap-5 sm:grid-cols-2"><Field label="Nome *" value={state.answers.name} onChange={value=>update("name",value)} autoComplete="name"/><Field label="WhatsApp com DDD *" value={state.answers.phone} onChange={value=>update("phone",maskPhone(value))} autoComplete="tel" inputMode="tel" placeholder="(00) 00000-0000"/></div><label className="mt-6 flex cursor-pointer items-start gap-3 rounded-xl border bg-cream p-4 text-sm leading-6"><input className="mt-1 h-5 w-5 accent-[#D2A34D]" type="checkbox" checked={Boolean(state.answers.serviceConsent)} onChange={event=>update("serviceConsent",event.target.checked)}/><span>Li o <Link className="font-bold underline" href="/privacidade" target="_blank">Aviso de Privacidade</Link> e autorizo a Cred Marvi a utilizar as informações fornecidas para preparar meu atendimento e entrar em contato comigo.</span></label><label className="mt-3 flex cursor-pointer items-start gap-3 px-4 text-sm leading-6 text-muted"><input className="mt-1 h-5 w-5 accent-[#D2A34D]" type="checkbox" checked={Boolean(state.answers.marketingConsent)} onChange={event=>update("marketingConsent",event.target.checked)}/><span>Quero receber novidades e informações da Cred Marvi.</span></label></div>;
 const objective=objectiveById(state.context.objectiveId)?.title||flowLabel(state.context);return <div className="divide-y rounded-2xl border bg-cream px-5"><Review label="Perfil" value={state.context.profile==="BUSINESS"?"Empresa":state.context.profile==="PERSON"?"Pessoa física":"Não informado"}/><Review label="Objetivo" value={objective}/>{state.answers.vehicleIntent&&<Review label="Contexto" value={answerLabels[state.answers.vehicleIntent]}/>} {state.answers.consortiumGoal&&<Review label="Conquista" value={answerLabels[state.answers.consortiumGoal]}/>} {state.answers.amountRange&&<Review label="Faixa aproximada" value={answerLabels[state.answers.amountRange]}/>} {state.answers.urgency&&<Review label="Prazo" value={answerLabels[state.answers.urgency]}/>}<Review label="Contato" value={`${state.answers.name} · ${state.answers.phone}`}/><p className="py-4 text-sm leading-6 text-muted"><ShieldCheck className="mr-2 inline text-[#8b6a16]" size={17}/>A mensagem do WhatsApp contém apenas protocolo, perfil e assunto.</p></div>
}
function Option({icon,label,text,onClick}:{icon?:React.ReactNode;label:string;text?:string;onClick:()=>void}){return <button type="button" onClick={onClick} className="option group"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full border border-gold/35 bg-gold/10 text-[#8b6a16]">{icon||<ArrowRight size={16}/>}</span><span><strong className="block">{label}</strong>{text&&<small className="mt-1 block font-medium leading-5 text-muted">{text}</small>}</span></button>}
function Field({label,value,onChange,placeholder,autoComplete,inputMode="text"}:{label:string;value?:string;onChange:(value:string)=>void;placeholder?:string;autoComplete:string;inputMode?:"text"|"tel"}){return <label><span className="mb-2 block text-sm font-bold">{label}</span><input className="field" value={value||""} onChange={event=>onChange(event.target.value)} placeholder={placeholder} autoComplete={autoComplete} inputMode={inputMode}/></label>}
function Review({label,value}:{label:string;value:string}){return <p className="py-4"><span className="block text-xs font-bold uppercase tracking-wider text-muted">{label}</span><strong className="mt-1 block">{value}</strong></p>}
function Shell({children,progress,onBack}:{children:React.ReactNode;progress:number;onBack:()=>void}){return <main id="conteudo" className="min-h-screen bg-canvas"><header className="border-b border-border-subtle bg-canvas/95 backdrop-blur-md"><div className="mx-auto flex h-[72px] max-w-5xl items-center justify-between gap-3 px-5"><button onClick={onBack} className="inline-flex min-h-11 items-center gap-2 rounded-xl px-2 text-sm font-bold text-navy transition hover:bg-white"><ArrowLeft size={17}/>Voltar</button><div className="scale-90"><Logo/></div><span className="flex min-w-11 items-center justify-end gap-2 text-xs font-bold text-muted"><Clock className="hidden sm:block" size={16}/>{progress}%</span></div><div className="h-1 bg-[#ebe8df]" role="progressbar" aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress} aria-label={`Progresso do atendimento: ${progress}%`}><div className="h-full rounded-r-full bg-gold transition-all duration-200" style={{width:`${progress}%`}}/></div></header><div className="mx-auto max-w-3xl px-5 py-10 sm:py-16 lg:py-20"><div className="rounded-[2rem] border border-border-subtle bg-white p-6 shadow-subtle sm:p-10">{children}</div><div className="mt-6 flex justify-center gap-2 text-xs text-muted"><LockKeyhole size={15}/><Link href="/privacidade" target="_blank" className="underline underline-offset-4">Seus dados e sua privacidade</Link></div></div></main>}
