import { z } from "zod"; import { validCnpj, normalizePhone } from "../formatting";
const optionalText=z.string().max(300).optional().or(z.literal(""));
export const leadSchema=z.object({
 customerType:z.enum(["PERSON","BUSINESS"]), need:z.string().min(1), otherNeed:optionalText, amountRange:z.string().optional(), urgency:z.string().min(1),
 businessName:z.string().max(150).optional(), cnpj:z.string().max(18).optional().refine(validCnpj,"Confira o CNPJ informado."), businessSegment:z.string().optional(), businessAgeRange:z.string().optional(), monthlyRevenueRange:z.string().optional(), employmentType:z.string().optional(), monthlyIncomeRange:z.string().optional(),
 fullName:z.string().trim().min(3,"Informe como podemos chamar você.").max(150).refine(v=>!/^[\d\s]+$/.test(v),"Informe como podemos chamar você."), phone:z.string().refine(v=>{const d=normalizePhone(v);return d.length===10||d.length===11},"Digite um número de WhatsApp válido com DDD."), email:z.string().email("Confira o formato do e-mail.").optional().or(z.literal("")), city:z.string().trim().min(2,"Informe sua cidade.").max(100), state:z.string().length(2,"Selecione seu estado."),
 serviceConsent:z.literal(true,{errorMap:()=>({message:"Para enviar a solicitação, leia e aceite o Aviso de Privacidade."})}), marketingConsent:z.boolean(), privacyNoticeVersion:z.string(), serviceConsentAt:z.string(), source:z.string().max(100).optional(), campaign:z.string().max(100).optional(), medium:z.string().max(100).optional(), content:z.string().max(100).optional(),status:z.literal("NEW"),honeypot:z.string().max(0).optional(),startedAt:z.number().optional()
}).strict().superRefine((d,c)=>{if(d.need==="Outro"&&(!d.otherNeed||d.otherNeed.trim().length<5))c.addIssue({code:"custom",path:["otherNeed"],message:"Conte brevemente o que você procura (mínimo de 5 caracteres)."});if(d.customerType==="BUSINESS"&&(!d.businessName||d.businessName.trim().length<2))c.addIssue({code:"custom",path:["businessName"],message:"Informe o nome da empresa."});});
export type LeadInput=z.input<typeof leadSchema>;
