export type Audience = "PERSON" | "BUSINESS" | "BOTH";
export type ProductStatus = "ACTIVE" | "INACTIVE" | "PENDING_CONFIRMATION";
export type Product = {id:string;slug:string;name:string;description:string;audience:Audience;categoryId:string;objectiveIds:string[];status:ProductStatus;featured:boolean;priority:number;operationalChannel:"DIRECT"|"COTAFACIL";requiresHumanReview:true};
export const categories=[["credit","Crédito"],["financing","Financiamentos"],["consortium","Consórcios"],["insurance","Seguros"],["business","Soluções empresariais"],["energy","Energia"],["health","Saúde e benefícios"],["travel","Viagens"],["other","Outras soluções"]] as const;
export const products:Product[]=[
{id:"real-estate",slug:"financiamento-de-imovel",name:"Financiamento de imóvel",description:"Alternativa para aquisição de imóvel.",audience:"PERSON",categoryId:"financing",objectiveIds:["buy-home"],status:"ACTIVE",featured:true,priority:10,operationalChannel:"DIRECT",requiresHumanReview:true},
{id:"vehicle",slug:"financiamento-de-veiculo",name:"Financiamento de veículo",description:"Alternativa para compra ou troca de veículo.",audience:"BOTH",categoryId:"financing",objectiveIds:["buy-vehicle","business-vehicle"],status:"ACTIVE",featured:true,priority:20,operationalChannel:"DIRECT",requiresHumanReview:true},
{id:"working-capital",slug:"capital-de-giro",name:"Capital de giro",description:"Alternativa para necessidades de caixa da empresa.",audience:"BUSINESS",categoryId:"business",objectiveIds:["cash-flow","working-capital"],status:"ACTIVE",featured:true,priority:30,operationalChannel:"DIRECT",requiresHumanReview:true},
{id:"consortium",slug:"consorcio",name:"Consórcio",description:"Planejamento para aquisições futuras.",audience:"BOTH",categoryId:"consortium",objectiveIds:["plan-purchase"],status:"ACTIVE",featured:true,priority:40,operationalChannel:"DIRECT",requiresHumanReview:true},
{id:"cotafacil-portfolio",slug:"cotafacil",name:"Portfólio CotaFácil",description:"Produtos aguardando validação comercial.",audience:"BOTH",categoryId:"other",objectiveIds:[],status:"PENDING_CONFIRMATION",featured:false,priority:999,operationalChannel:"COTAFACIL",requiresHumanReview:true}];
export const publicProducts=products.filter(product=>product.status==="ACTIVE");
export const cotafacilConfig={enabled:true,publicBrandingEnabled:false,products:[] as string[],institutions:[] as string[],logosAllowed:false,city:"",unitIdentifier:""};
