import type {Audience} from "./catalog";
export type Objective={id:string;slug:string;audience:Audience;title:string;shortDescription:string;categoryIds:string[];productIds:string[];active:boolean;priority:number};
export const objectives:Objective[]=[
{id:"buy-home",slug:"comprar-casa",audience:"PERSON",title:"Comprar uma casa",shortDescription:"Entender alternativas para aquisição de imóvel.",categoryIds:["financing","consortium"],productIds:["real-estate","consortium"],active:true,priority:10},
{id:"buy-vehicle",slug:"comprar-trocar-carro",audience:"PERSON",title:"Comprar ou trocar de carro",shortDescription:"Avaliar caminhos para seu próximo veículo.",categoryIds:["financing","consortium"],productIds:["vehicle","consortium"],active:true,priority:20},
{id:"get-credit",slug:"conseguir-credito",audience:"PERSON",title:"Conseguir crédito",shortDescription:"Organizar sua necessidade antes de avaliar alternativas.",categoryIds:["credit"],productIds:[],active:true,priority:30},
{id:"organize-debt",slug:"organizar-dividas",audience:"PERSON",title:"Organizar dívidas",shortDescription:"Explicar seu cenário para um atendimento direcionado.",categoryIds:["credit"],productIds:[],active:true,priority:40},
{id:"plan-purchase",slug:"planejar-compra",audience:"PERSON",title:"Planejar uma compra",shortDescription:"Conhecer possibilidades para um objetivo futuro.",categoryIds:["consortium"],productIds:["consortium"],active:true,priority:50},
{id:"protect-family",slug:"proteger-familia",audience:"PERSON",title:"Proteger minha família ou patrimônio",shortDescription:"Preparar uma conversa sobre proteção.",categoryIds:["insurance"],productIds:[],active:true,priority:60},
{id:"reduce-personal-costs",slug:"reduzir-custos-pessoais",audience:"PERSON",title:"Reduzir alguns custos",shortDescription:"Conhecer alternativas que possam ajudar na eficiência dos gastos.",categoryIds:["energy","other"],productIds:[],active:true,priority:70},
{id:"health-wellbeing",slug:"saude-bem-estar",audience:"PERSON",title:"Saúde e bem-estar",shortDescription:"Conhecer soluções disponíveis relacionadas a cuidado e conveniência.",categoryIds:["health"],productIds:[],active:true,priority:80},
{id:"plan-trip",slug:"planejar-viagem",audience:"PERSON",title:"Planejar uma viagem",shortDescription:"Conhecer alternativas disponíveis para uma viagem.",categoryIds:["travel"],productIds:[],active:true,priority:90},
{id:"cash-flow",slug:"reforcar-caixa",audience:"BUSINESS",title:"Reforçar o fluxo de caixa",shortDescription:"Avaliar alternativas para a operação da empresa.",categoryIds:["business","credit"],productIds:["working-capital"],active:true,priority:10},
{id:"working-capital",slug:"capital-de-giro",audience:"BUSINESS",title:"Conseguir capital de giro",shortDescription:"Preparar a necessidade de crédito empresarial.",categoryIds:["business","credit"],productIds:["working-capital"],active:true,priority:20},
{id:"business-vehicle",slug:"financiar-veiculo",audience:"BUSINESS",title:"Financiar veículo",shortDescription:"Avaliar aquisição em nome da empresa.",categoryIds:["financing"],productIds:["vehicle"],active:true,priority:30},
{id:"expand",slug:"investir-expansao",audience:"BUSINESS",title:"Investir em expansão",shortDescription:"Organizar o próximo investimento do negócio.",categoryIds:["business","credit"],productIds:[],active:true,priority:40},
{id:"reduce-costs",slug:"reduzir-custos",audience:"BUSINESS",title:"Reduzir custos",shortDescription:"Apresentar seu cenário para identificar possibilidades.",categoryIds:["energy","business"],productIds:[],active:true,priority:50},
{id:"protect-business",slug:"proteger-empresa",audience:"BUSINESS",title:"Proteger a empresa",shortDescription:"Conhecer alternativas de proteção para patrimônio e operação.",categoryIds:["insurance","business"],productIds:[],active:true,priority:60},
{id:"people-benefits",slug:"pessoas-beneficios",audience:"BUSINESS",title:"Pessoas e benefícios",shortDescription:"Conhecer soluções disponíveis para equipe ou gestão.",categoryIds:["health","business"],productIds:[],active:true,priority:70},
{id:"unsure-person",slug:"nao-sei-pf",audience:"PERSON",title:"Ainda não sei qual solução preciso",shortDescription:"Tudo bem. Conte seu objetivo e a especialista direciona o atendimento.",categoryIds:["other"],productIds:[],active:true,priority:999},
{id:"unsure-business",slug:"nao-sei-pj",audience:"BUSINESS",title:"Ainda não sei qual solução preciso",shortDescription:"Conte o momento da empresa e prepare o atendimento.",categoryIds:["other"],productIds:[],active:true,priority:999}];
export const objectivesFor=(audience:"PERSON"|"BUSINESS")=>objectives.filter(item=>item.active&&(item.audience===audience||item.audience==="BOTH")).sort((a,b)=>a.priority-b.priority);
export const objectiveById=(id?:string)=>objectives.find(item=>item.id===id);
