export const digits = (value:string) => value.replace(/\D/g, "");
export function maskPhone(value:string){ const d=digits(value).slice(0,11); return d.length<=10?d.replace(/^(\d{0,2})(\d{0,4})(\d{0,4}).*/,(_,a,b,c)=>`${a?`(${a}${a.length===2?") ":""}`:""}${b}${c?`-${c}`:""}`):d.replace(/^(\d{2})(\d{5})(\d{0,4}).*/,"($1) $2-$3"); }
export const normalizePhone = (value:string) => digits(value);
export function maskCpf(value:string){return digits(value).slice(0,11).replace(/^(\d{3})(\d)/,"$1.$2").replace(/^(\d{3})\.(\d{3})(\d)/,"$1.$2.$3").replace(/(\d{3})(\d{1,2})$/,"$1-$2")}
export function maskRg(value:string){const n=value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,9);if(n.length<=2)return n;if(n.length<=5)return `${n.slice(0,2)}.${n.slice(2)}`;if(n.length<=8)return `${n.slice(0,2)}.${n.slice(2,5)}.${n.slice(5)}`;return `${n.slice(0,2)}.${n.slice(2,5)}.${n.slice(5,8)}-${n.slice(8)}`}
export function maskMoney(value:string){const n=digits(value);if(!n)return "";return new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL",maximumFractionDigits:0}).format(Number(n))}
export function maskVehicleYear(value:string){return digits(value).slice(0,4)}
export function maskVehiclePlate(value:string){const n=value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,7);return /^[A-Z]{3}\d{1,4}$/.test(n)?`${n.slice(0,3)}-${n.slice(3)}`:n}
export function normalizeCnpj(value:string){return value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,14)}
export function maskCnpj(value:string){const raw=normalizeCnpj(value),base=raw.slice(0,12),dv=raw.slice(12).replace(/\D/g,"");const n=`${base}${dv}`;if(n.length<=2)return n;if(n.length<=5)return `${n.slice(0,2)}.${n.slice(2)}`;if(n.length<=8)return `${n.slice(0,2)}.${n.slice(2,5)}.${n.slice(5)}`;if(n.length<=12)return `${n.slice(0,2)}.${n.slice(2,5)}.${n.slice(5,8)}/${n.slice(8)}`;return `${n.slice(0,2)}.${n.slice(2,5)}.${n.slice(5,8)}/${n.slice(8,12)}-${n.slice(12)}`}
export function validCnpj(value?:string){if(!value)return true;const n=normalizeCnpj(value);if(!/^[A-Z0-9]{12}\d{2}$/.test(n)||/^(\d)\1{13}$/.test(n))return false;const calc=(base:string,f:number)=>{let sum=0;for(const x of base){sum+=(x.charCodeAt(0)-48)*f;f--;if(f===1)f=9}return sum%11<2?0:11-sum%11};return calc(n.slice(0,12),5)===Number(n[12])&&calc(n.slice(0,13),6)===Number(n[13])}
