export type SolutionGuide = {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  audience: string;
  profile: "PERSON" | "BUSINESS";
  solution: string;
  introduction: string;
  suitableFor: string[];
  initialInfo: string[];
  questions: [string,string][];
};

export const solutionGuides:SolutionGuide[]=[
  {slug:"financiamento-de-imovel",title:"Financiamento de imóvel",shortTitle:"Financiamento de imóvel",description:"Entenda como funciona a análise inicial para financiamento de imóvel e quais informações ajudam a avaliar a solicitação.",audience:"pessoas físicas",profile:"PERSON",solution:"REAL_ESTATE_FINANCING",introduction:"O financiamento de imóvel pode apoiar a compra de uma propriedade com pagamento ao longo do prazo definido pela instituição financeira. Na análise, condições como valor do imóvel, entrada, renda e capacidade de pagamento são consideradas.",suitableFor:["Quem pretende comprar um imóvel e financiar parte do valor","Quem quer organizar previamente as informações da solicitação","Quem busca atendimento para compreender as alternativas disponíveis"],initialInfo:["Valor aproximado do imóvel","Valor que pretende financiar","Renda mensal","Dados pessoais e informações de contato"],questions:[["O preenchimento garante a aprovação?","Não. Aprovação, prazo, taxa e demais condições dependem da análise e dos critérios da instituição responsável."],["Preciso enviar documentos pelo site?","Não. O formulário inicial não recebe arquivos ou fotos de documentos. Caso sejam necessários depois, a especialista orientará o canal adequado."],["Posso preencher o formulário a qualquer hora?","Sim. O formulário fica disponível 24 horas e o atendimento ocorre em horário comercial."]]},
  {slug:"financiamento-de-veiculo",title:"Financiamento de veículo",shortTitle:"Financiamento de veículo",description:"Veja quais informações são consideradas no atendimento inicial para financiar veículo usado ou zero km, como pessoa física ou empresa.",audience:"pessoas físicas e empresas",profile:"PERSON",solution:"VEHICLE",introduction:"O financiamento de veículo permite avaliar a compra de um automóvel usado ou zero km. O atendimento inicial é direcionado conforme o comprador seja pessoa física ou empresa e conforme a condição do veículo.",suitableFor:["Compra de veículo usado","Compra de veículo zero km","Aquisição em nome de pessoa física ou empresa"],initialInfo:["Condição, valor, marca e modelo do veículo","Ano e placa, quando o veículo for usado","CPF ou CNPJ do comprador","Endereço e informações de contato"],questions:[["A análise atende pessoas e empresas?","Sim. Ao começar, escolha o perfil correto para que o formulário solicite CPF ou CNPJ conforme o comprador."],["Quais condições serão apresentadas?","Taxa, prazo, entrada e aprovação dependem da análise e das regras da instituição responsável."],["Já preciso ter escolhido o veículo?","As informações do veículo ajudam a direcionar o atendimento. Para zero km, o formulário solicita os dados relacionados à nota fiscal, marca e modelo."]]},
  {slug:"capital-de-giro",title:"Capital de giro para empresas",shortTitle:"Capital de giro",description:"Saiba como organizar uma solicitação de capital de giro para apoiar o caixa, as compras ou os investimentos da empresa.",audience:"empresas",profile:"BUSINESS",solution:"CREDIT_BUSINESS",introduction:"O capital de giro é uma alternativa de crédito empresarial que pode apoiar necessidades operacionais, compras e investimentos. A análise considera o perfil da empresa, o valor solicitado, o faturamento e as condições disponíveis.",suitableFor:["Apoiar o fluxo de caixa da empresa","Organizar compras e necessidades operacionais","Avaliar recursos para investimentos empresariais"],initialInfo:["Valor de capital de giro pretendido","CNPJ, nome da empresa e faturamento mensal","Garantias disponíveis, quando aplicável","Dados do sócio administrador e contato"],questions:[["Toda empresa consegue contratar?","A disponibilidade e a aprovação dependem do perfil da empresa e dos critérios de cada instituição."],["É obrigatório oferecer garantia?","As exigências variam conforme a operação e a instituição. No atendimento inicial, você pode informar as garantias disponíveis."],["O formulário já contrata o crédito?","Não. Ele organiza as informações para o atendimento inicial e não constitui proposta ou concessão de crédito."]]},
  {slug:"consorcio",title:"Consórcio para imóveis, veículos, pesados e serviços",shortTitle:"Consórcio",description:"Conheça o atendimento inicial para consórcio de imóveis, veículos, pesados ou serviços para pessoas e empresas.",audience:"pessoas físicas e empresas",profile:"PERSON",solution:"CONSORTIUM",introduction:"O consórcio é uma modalidade de compra planejada em grupo. A utilização do crédito ocorre após a contemplação, conforme as regras do grupo e da administradora. O atendimento ajuda a identificar a categoria e o valor pretendido.",suitableFor:["Planejamento para adquirir imóvel ou veículo","Aquisição de veículos pesados por pessoa ou empresa","Contratação de serviços dentro das categorias disponíveis"],initialInfo:["Categoria do bem ou serviço","Valor pretendido","CPF ou CNPJ","Telefone e e-mail para contato"],questions:[["Consórcio tem aprovação imediata?","Não. A participação, a contemplação e a utilização do crédito seguem as regras e análises da administradora responsável."],["Como acontece a contemplação?","Ela ocorre conforme as regras do grupo, geralmente por sorteio ou lance. As condições específicas são apresentadas pela instituição responsável."],["Pessoa jurídica pode solicitar?","Sim. Ao acessar pela opção para empresas, o fluxo solicita o CNPJ e identifica o atendimento como pessoa jurídica."]]}
];

export const guideBySlug=(slug:string)=>solutionGuides.find(guide=>guide.slug===slug);
